language: node_js
node_js:
  - "6"
before_script:
  - npm install -g gulp
  - psql -c 'create database testing_pandoras_kits;' -U postgres
  - psql -c 'create database pandoras_kits;' -U postgres
script: gulp build
branches:
  only:
    - master
services:
  - postgresql
after_success:
  - npm test
  - npm run coveralls
  - rm -rf ./coverage
